// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilfielmaafrvkdxodawp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsZmllbG1hYWZydmtkeG9kYXdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzNjc5NDYsImV4cCI6MjA1MDk0Mzk0Nn0.ZRxz0cfF7ATdDXxiRMe4JcX2AzIuwtaq9maupWm9uT8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);